#ifndef INCLUDED_CHATSERVER_INSTRUCTIONTYPES_HPP
#define INCLUDED_CHATSERVER_INSTRUCTIONTYPES_HPP

enum InstructionType
{
	UNKNOWN,
	RECEIVE_MESSAGE,
	RESPOND_CREATE_USER,
	RESPOND_FIND_USER
};

#endif
